In [220]:
import gym
import numpy as np

env = gym.make("Taxi-v3").env

print("Action Space {}".format(env.action_space))
print("State Space {}".format(env.observation_space))

state = env.encode(3, 1, 2, 0)  # (taxi row, taxi column, passenger index, destination index)
print("State:", state)
env.s = state
# env.render()

env.P[328]

Action Space Discrete(6)
State Space Discrete(500)
State: 328


{0: [(1.0, 428, -1, False)],
 1: [(1.0, 228, -1, False)],
 2: [(1.0, 348, -1, False)],
 3: [(1.0, 328, -1, False)],
 4: [(1.0, 328, -10, False)],
 5: [(1.0, 328, -10, False)]}

In [221]:

epochs = 0
penalties, reward = 0, 0

done = False

while not done:
    action = env.action_space.sample()
    state, reward, done, info = env.step(action)

    if reward == -10:
        penalties += 1

    epochs += 1

print("Timesteps taken: {}".format(epochs))
print("Penalties incurred: {}".format(penalties))

Timesteps taken: 407
Penalties incurred: 125


In [222]:
q_table = np.zeros([env.observation_space.n, env.action_space.n])
print(q_table)
print(q_table.shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(500, 6)


In [223]:
import random
from IPython.display import clear_output

# Hyperparameters
alpha = 0.1
gamma = 0.6
epsilon = 0.1

# For plotting metrics
all_epochs = []
all_penalties = []

for i in range(1, 222):
    state = env.reset()

    epochs, penalties, reward, = 0, 0, 0
    done = False

    while not done:
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample() # Explore action space
        else:
            action = np.argmax(q_table[state]) # Exploit learned values

        next_state, reward, done, info = env.step(action)

        old_value = q_table[state, action]
        next_max = np.max(q_table[next_state])

        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_value

        if reward == -10:
            penalties += 1
            # print('penalizacion!!')

        state = next_state
        epochs += 1

    if i % 100 == 0:
        clear_output(wait=True)
        print(f"Episode: {i}")

print("Training finished.\n")

Episode: 200
Training finished.



In [224]:
# q_table[328]
print(q_table)
print(q_table.shape)

[[ 0.          0.          0.          0.          0.          0.        ]
 [-2.04003172 -2.03030084 -2.02966941 -2.04683495 -2.04182511 -4.38986281]
 [-1.66148689 -1.6694922  -1.64893535 -1.66834808 -1.64862871 -5.5900142 ]
 ...
 [-1.08464046 -1.08369586 -1.08787155 -1.07984728 -1.96       -1.96      ]
 [-1.90053668 -1.91534803 -1.90099125 -1.91511989 -1.96       -3.63199137]
 [-0.196      -0.196      -0.196      -0.07       -1.         -1.        ]]
(500, 6)


In [225]:
"""Evaluate agent's performance after Q-learning"""

total_epochs, total_penalties, total_aciertos = 0, 0, 0
episodes = 100

for _ in range(episodes):
    state = env.reset()
    epochs, penalties, reward = 0, 0, 0
    acierto=0

    done = False

    print('cuantas',_)

    while epochs<30 and reward != -10 and not done:
        action = np.argmax(q_table[state])
        state, reward, done, info = env.step(action)
        # print('bucle while')

        if reward == -10 or epochs == 29:
            penalties += 1
            print('penalizacion!')

        if done:
            print('acierto')
            acierto += 1
        epochs += 1


    total_penalties += penalties
    total_epochs += epochs
    total_aciertos += acierto

print(f"Results after {episodes} episodes:")
print(f"Total penalties: {total_penalties}")
print(f"Total aciertos: {total_aciertos}")
# print(f"Average timesteps per episode: {total_epochs / episodes}")
# print(f"Average penalties per episode: {total_penalties / episodes}")


cuantas 0
penalizacion!
cuantas 1
penalizacion!
cuantas 2
penalizacion!
cuantas 3
penalizacion!
cuantas 4
penalizacion!
cuantas 5
penalizacion!
cuantas 6
penalizacion!
cuantas 7
penalizacion!
cuantas 8
penalizacion!
cuantas 9
penalizacion!
cuantas 10
penalizacion!
cuantas 11
penalizacion!
cuantas 12
penalizacion!
cuantas 13
penalizacion!
cuantas 14
penalizacion!
cuantas 15
penalizacion!
cuantas 16
penalizacion!
cuantas 17
penalizacion!
cuantas 18
penalizacion!
cuantas 19
penalizacion!
cuantas 20
penalizacion!
cuantas 21
penalizacion!
cuantas 22
penalizacion!
cuantas 23
penalizacion!
cuantas 24
penalizacion!
cuantas 25
penalizacion!
cuantas 26
penalizacion!
cuantas 27
penalizacion!
cuantas 28
penalizacion!
cuantas 29
acierto
cuantas 30
penalizacion!
cuantas 31
penalizacion!
cuantas 32
penalizacion!
cuantas 33
penalizacion!
cuantas 34
penalizacion!
cuantas 35
penalizacion!
cuantas 36
penalizacion!
cuantas 37
penalizacion!
cuantas 38
penalizacion!
cuantas 39
penalizacion!
cuantas 40
penal